"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from distutils.core import setup
import py2app

APP = ['k40_whisperer.py']
APP_NAME = "K40 Whisperer"
DATA_FILES = ['right.png','left.png','up.png','down.png','UL.png','UR.png','LR.png','LL.png','CC.png','emblem','emblem64']
OPTIONS = {
	'iconfile': 'k40_whisperer.icns',
	"includes": ["lxml.etree", "lxml._elementpath", "gzip"],
	"compressed": 1, "optimize": 0,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Making Sandwiches",
        'CFBundleIdentifier': "com.scorchworks.osx.k40_whisperer",
        'CFBundleVersion': "0.27",
        'CFBundleShortVersionString': "0.27",
        'NSHumanReadableCopyright': u"Copyright  2017, Scorch Works, GNU General Public License",
        'NSHighResolutionCapable': True
    }
}
setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
